# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal_show_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 2, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(1320, 1000))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.verticalLayout_10.addLayout(self.verticalLayout1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.verticalLayout_8.addLayout(self.verticalLayout2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(False)
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout3 = QtWidgets.QVBoxLayout()
        self.verticalLayout3.setObjectName("verticalLayout3")
        self.verticalLayout_6.addLayout(self.verticalLayout3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_4.sizePolicy().hasHeightForWidth())
        self.tab_4.setSizePolicy(sizePolicy)
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout4 = QtWidgets.QVBoxLayout()
        self.verticalLayout4.setObjectName("verticalLayout4")
        self.verticalLayout_4.addLayout(self.verticalLayout4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setEnabled(False)
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout5 = QtWidgets.QVBoxLayout()
        self.verticalLayout5.setObjectName("verticalLayout5")
        self.horizontalLayout_4.addLayout(self.verticalLayout5)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setEnabled(False)
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout6 = QtWidgets.QVBoxLayout()
        self.verticalLayout6.setObjectName("verticalLayout6")
        self.horizontalLayout_5.addLayout(self.verticalLayout6)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 2, 3, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionasave = QtWidgets.QAction(MainWindow)
        self.actionasave.setObjectName("actionasave")
        self.actionedit = QtWidgets.QAction(MainWindow)
        self.actionedit.setObjectName("actionedit")
        self.actionview = QtWidgets.QAction(MainWindow)
        self.actionview.setObjectName("actionview")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionexcel = QtWidgets.QAction(MainWindow)
        self.actionexcel.setObjectName("actionexcel")
        self.actionreport = QtWidgets.QAction(MainWindow)
        self.actionreport.setObjectName("actionreport")
        self.actionzdata = QtWidgets.QAction(MainWindow)
        self.actionzdata.setCheckable(True)
        self.actionzdata.setObjectName("actionzdata")
        self.actionhdata = QtWidgets.QAction(MainWindow)
        self.actionhdata.setCheckable(True)
        self.actionhdata.setObjectName("actionhdata")
        self.actionbdata = QtWidgets.QAction(MainWindow)
        self.actionbdata.setCheckable(True)
        self.actionbdata.setObjectName("actionbdata")
        self.actionpitch = QtWidgets.QAction(MainWindow)
        self.actionpitch.setCheckable(True)
        self.actionpitch.setObjectName("actionpitch")
        self.actionroll = QtWidgets.QAction(MainWindow)
        self.actionroll.setCheckable(True)
        self.actionroll.setObjectName("actionroll")
        self.actionheading = QtWidgets.QAction(MainWindow)
        self.actionheading.setCheckable(True)
        self.actionheading.setObjectName("actionheading")
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionindextable = QtWidgets.QAction(MainWindow)
        self.actionindextable.setCheckable(True)
        self.actionindextable.setObjectName("actionindextable")
        self.action3d = QtWidgets.QAction(MainWindow)
        self.action3d.setCheckable(True)
        self.action3d.setObjectName("action3d")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionasave)
        self.menu.addAction(self.actionexcel)
        self.menu.addAction(self.actionreport)
        self.menu_2.addAction(self.actionedit)
        self.menu_2.addAction(self.actionquit)
        self.menu_3.addAction(self.actionzdata)
        self.menu_3.addAction(self.actionhdata)
        self.menu_3.addAction(self.actionbdata)
        self.menu_3.addAction(self.actionpitch)
        self.menu_3.addAction(self.actionroll)
        self.menu_3.addAction(self.actionheading)
        self.menu_3.addAction(self.actionindextable)
        self.menu_3.addAction(self.action3d)
        self.menu_4.addAction(self.actionhelp)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addSeparator()
        self.toolBar_3.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "浏览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "磁垂直分量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "磁水平分量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "磁总量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "罗盘俯仰角"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "罗盘横滚角"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "罗盘方位角"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "数据表格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "运动轨迹"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "视图"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("MainWindow", "保存"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionasave.setText(_translate("MainWindow", "另存为"))
        self.actionedit.setText(_translate("MainWindow", "编辑"))
        self.actionview.setText(_translate("MainWindow", "视图"))
        self.actionhelp.setText(_translate("MainWindow", "帮助"))
        self.actionexcel.setText(_translate("MainWindow", "导出表格"))
        self.actionexcel.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionreport.setText(_translate("MainWindow", "导出报告"))
        self.actionreport.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionzdata.setText(_translate("MainWindow", "磁垂直分量"))
        self.actionhdata.setText(_translate("MainWindow", "磁水平分量"))
        self.actionbdata.setText(_translate("MainWindow", "磁总量"))
        self.actionpitch.setText(_translate("MainWindow", "罗盘俯仰角"))
        self.actionroll.setText(_translate("MainWindow", "横滚角"))
        self.actionheading.setText(_translate("MainWindow", "方位角"))
        self.actionquit.setText(_translate("MainWindow", "退出"))
        self.actionquit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionindextable.setText(_translate("MainWindow", "数据表格"))
        self.action3d.setText(_translate("MainWindow", "运动轨迹"))
